AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  capture-page-from-url

  Sample SAM Template for capture-page-from-url
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 600000
    MemorySize: 512

Resources:
  CapturePageApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  CapturePageFromUrl:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: post
          RestApiId:
            Ref: CapturePageApi

    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./capture-page-from-url/
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  CapturePageFromUrl:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt CapturePageFromUrl.Arn
  CapturePageFromUrlIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt CapturePageFromUrlRole.Arn
